on: push
name: Example Workflow
jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 11 # This value must be set if the lookback configuration option is not disabled for find-code-references. Read more: https://github.com/launchdarkly/ld-find-code-refs#searching-for-unused-flags-extinctions
      - name: LaunchDarkly Code References
        uses: launchdarkly/find-code-references@v9
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          accessToken: ${{ secrets.LD_ACCESS_TOKEN }}
          projKey: Actual-chart
